blank_issues_enabled: true
contact_links:
  - name: Security Policy
    url: https://github.com/ATAC-Helicopter/Blueprints/blob/main/SECURITY.md
    about: Please report security issues according to the security policy.
